# Generated by Django 5.1.2 on 2024-10-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_titile_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='simple_discription',
            new_name='simple_description',
        ),
    ]
