# Generated by Django 5.1.2 on 2024-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
